#ifndef QT5UKUIPLATFORMTHEME_GLOBAL_H
#define QT5UKUIPLATFORMTHEME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT5UKUIPLATFORMTHEME_LIBRARY)
#  define QT5UKUIPLATFORMTHEMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QT5UKUIPLATFORMTHEMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QT5UKUIPLATFORMTHEME_GLOBAL_H
